### ISSUE TITLE
[依頼]最終課題挙動確認

### ISSUE THREAD

**Issue by kudoushinichiro** [kudoushinichiro/fleamarket_sample_72d#81]
■ URL
IPアドレス：http://18.180.94.77

Github（最終課題のリポジトリ）：https://github.com/kudoushinichiro/fleamarket_sample_72d

■ Basic認証
ID：admind
Pass：7272

■ テスト用アカウント
◯ 購入者用
メールアドレス：buy72d@gmail.com
パスワード：buy1234

◯ 購入用カード情報
番号：4242424242424242
期限：12/25
セキュリティコード：123

◯ 出品者用
メールアドレス：sell72d@gmail.com
パスワード：sell1234

**Comment by kubota-tec** [comment]
72期dチームさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**新規登録時**
①氏名(全角)がアルファベットでも登録できてしまいます
②氏名フリガナ(カナ)が平仮名でも登録できてしまいます
https://gyazo.com/420382bb21a3de38c75d7053b3623deb

**商品出品時**
カテゴリーが選択できません
（それ以降の登録作業が進められない為挙動確認できておりません）
https://gyazo.com/cab025e670c1750b893133a378243c97

**その他**
テスト購入者の出品が少なくとも3つ以上ありません。
その後の挙動の確認もさせていただきますので、投稿お願いいたします。
また、その際には下記３点ご注意ください。
・画像がフリー素材、もしくはご自身で撮った写真であること
・適正な金額設定であること
・既存のサービス名やロゴなどを使用していないこと


こちらのサイトは企業様や仕事の案件を紹介していただける方が直接見るサイトですので
公序良俗、著作権に反する画像の使用をしない、不適切な文言を入れていないなども確認するようお願いいたします！



修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by kudoushinichiro** [comment]
すみません、まだ完成しておらず完成後すぐに最終課題完了報告フォームで提出できるようにissueのみ作成しておりました。
紛らわしくて申し訳ないです。

完成しましたらフォームの方から依頼をさせて頂きますのでよろしくお願い致します。

**Comment by kudoushinichiro** [comment]
提出させていただきました！ギリギリですがよろしくお願い致します！

**Comment by divyumi** [comment]
72期dチームさん、ご提出ありがとうございます！
必須機能については、今回問題ございませんでしたので、LGTMとさせていただきます。

ご参考までにですが、気になった箇所がございますので提示させて頂きます。
①選べるカテゴリの数が極端に少ない
→可能であれば企業に提出前に修正可能であれば増やしておけると良いかと！
②出品時の¥マークのビューに崩れが見られます。
→修正しておきましょう！
<img width="567" alt="スクリーンショット 2020-08-15 15 28 58" src="https://user-images.githubusercontent.com/48047141/90306870-29ac9800-df0c-11ea-9588-14df9de9a52c.png">

**Comment by kudoushinichiro** [comment]
ありがとうございます！
承知致しました！
